// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STARListener.Api.Data;

#nullable disable

namespace STARListener.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812011841_AddPontuacaoPorIntervaloData")]
    partial class AddPontuacaoPorIntervaloData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STARListener.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NivelCriticidade")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_criticidade");

                    b.Property<int>("NivelPrioridade")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_prioridade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("STARListener.Models.PontuacaoCriticidade", b =>
                {
                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.HasKey("Nivel")
                        .HasName("pk_pontuacoes_criticidade");

                    b.ToTable("pontuacoes_criticidade", (string)null);
                });

            modelBuilder.Entity("STARListener.Models.PontuacaoData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AteDiasAtras")
                        .HasColumnType("integer")
                        .HasColumnName("ate_dias_atras");

                    b.Property<int>("DeDiasAtras")
                        .HasColumnType("integer")
                        .HasColumnName("de_dias_atras");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.HasKey("Id")
                        .HasName("pk_pontuacoes_data");

                    b.ToTable("pontuacoes_data", (string)null);
                });

            modelBuilder.Entity("STARListener.Models.PontuacaoPrioridade", b =>
                {
                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.HasKey("Nivel")
                        .HasName("pk_pontuacoes_prioridade");

                    b.ToTable("pontuacoes_prioridade", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
